version: '3'

services:
    dronegames:
        build: .
        container_name: dronegames
        hostname: dronegames
        privileged: true
        ipc: host
        devices:
            - "/dev/fuse:/dev/fuse:rwm"
        cap_add:
            - SYS_ADMIN
        volumes:
            - "/tmp/.X11-unix:/tmp/.X11-unix"
            - ~/drone-games/sim_worlds/afs:/home/asad/drone-games/airsim/afs/:rw
            - ~/drone-games/sim_worlds/race:/home/asad/drone-games/airsim/race/:rw
            - ~/drone-games/sim_worlds/formation:/home/asad/drone-games/airsim/formation/:rw
            - ~/drone-games/sim_worlds/cargo:/home/asad/drone-games/airsim/cargo/:rw
            - ~/drone-games/sim_worlds/afs_heightmap.png:/home/asad/drone-games/airsim/afs_heightmap.png/:rw
            - ~/drone-games/solution:/home/asad/catkin_ws/src/solution/:rw 
            - ~/.Xauthority:/home/asad/.Xauthority
        ports:
            - "11311:11311"
        environment:
            - "DISPLAY=$DISPLAY"
            - "ROS_HOSTNAME=dronegames"
            - "ROS_MASTER_URI=http://127.0.0.1:11311"